global:
  scrape_interval: 5s
  external_labels:
    monitor: 'process-exporter'
scrape_configs:
  - job_name: 'prometheus' 
    static_configs: 
      - targets: ['hostip:9090'] ## IP Address of the localhost
  - job_name: 'process_exporter' 
    static_configs: 
      - targets: ['hostip:9256'] ## IP Address of the localhost
