{
 "title": "Monitor Pod CPU and Memory usage Copy",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "app",
    "label": "App",
    "query": {
     "query": "label_values(kube_pod_owner{owner_kind=~\"DaemonSet|StatefulSet|ReplicaSet|Node\"},owner_name)"
    }
   },
   {
    "name": "pod",
    "label": "Pod",
    "query": {
     "query": "label_values(kube_pod_owner{owner_name=\"$app\"},pod)"
    }
   },
   {
    "name": "container",
    "label": "Container",
    "query": {
     "query": "label_values(kube_pod_container_info{pod=\"$pod\"},container)"
    }
   }
  ]
 },
 "panels": [
  { "title": "CPU metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU(cores)",
   "type": "gauge",
   "gridPos": { "h": 17, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(kube_pod_container_resource_requests{pod=\"$pod\",container=\"$container\",resource=\"cpu\"}) by (container)",
     "legendFormat": "container-request"
    },
    {
     "expr": "round(quantile_over_time(0.95, max(rate(container_cpu_usage_seconds_total{pod=\"$pod\",container=\"$container\"}[1m])) by (container)[$__range:]), 0.001)",
     "legendFormat": "container-95th-percentile-usage"
    },
    {
     "expr": "round(max_over_time(max(rate(container_cpu_usage_seconds_total{pod=\"$pod\",container=\"$container\"}[1m])) by (container)[$__range:]), 0.001)",
     "legendFormat": "container-max-usage"
    },
    {
     "expr": "max(kube_pod_container_resource_limits{pod=\"$pod\",container=\"$container\",resource=\"cpu\"}) by (container)",
     "legendFormat": "container-limit"
    }
   ]
  },
  {
   "title": "CPU(cores)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{pod=\"$pod\",container=\"$container\"}[1m])) by (container)",
     "legendFormat": "container-usage"
    },
    {
     "expr": "max(kube_pod_container_resource_requests{pod=\"$pod\",container=\"$container\",resource=\"cpu\"}) by (container)",
     "legendFormat": "container-request"
    },
    {
     "expr": "max(kube_pod_container_resource_limits{pod=\"$pod\",container=\"$container\",resource=\"cpu\"}) by (container)",
     "legendFormat": "container-limit"
    },
    {
     "expr": "sum(increase(container_cpu_cfs_throttled_periods_total{pod=\"$pod\",container=\"$container\"}[1m])) / ignoring(id) sum(increase(container_cpu_cfs_periods_total{}[5m]))",
     "legendFormat": "throttling"
    }
   ]
  },
  {
   "title": "Number of Pods",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "targets": [
    { "expr": "kubelet_running_pods", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Row title",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "panels": [
    {
     "title": "Memory(Mi)",
     "type": "gauge",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 19 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "max(kube_pod_container_resource_requests{container=\"$container\",pod=\"$pod\",resource=\"memory\"}) by (container) / (1024*1024)",
       "legendFormat": "container-request"
      },
      {
       "expr": "quantile_over_time(0.95, max(container_memory_working_set_bytes{container=\"$container\",pod=\"$pod\"} / (1024*1024)) by (container)[$__range:])",
       "legendFormat": "container-95th-percentile-usage"
      },
      {
       "expr": "max_over_time( max(container_memory_working_set_bytes{container=\"$container\",pod=\"$pod\"} / (1024*1024)) by (container)[$__range:])",
       "legendFormat": "container-max-usage"
      }
     ]
    },
    {
     "title": "Memory(Mi)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 19 },
     "targets": [
      {
       "expr": "max(container_memory_working_set_bytes{container=\"$container\",pod=\"$pod\"} / (1024*1024)) by (container)",
       "legendFormat": "container-usage"
      },
      {
       "expr": "max(kube_pod_container_resource_requests{container=\"$container\",pod=\"$pod\",resource=\"memory\"}) by (container) / (1024*1024)",
       "legendFormat": "container-request"
      },
      {
       "expr": "max(kube_pod_container_resource_limits{container=\"$container\",pod=\"$pod\",resource=\"memory\"}) by (container) / (1024*1024)",
       "legendFormat": "container-limit"
      }
     ]
    }
   ]
  }
 ]
}